version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    assignees:
      - "avarayr"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates together
    groups:
      # Group all patch updates for non-major dependencies
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Group all updates for React ecosystem
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "next"
      # Group all updates for Radix UI components
      radix-ui:
        patterns:
          - "@radix-ui/*"
      # Group all updates for Tailwind CSS ecosystem
      tailwind-ecosystem:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "tailwind-merge"
          - "class-variance-authority"
      # Group all updates for TypeScript ecosystem
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
      # Group all updates for ESLint ecosystem
      eslint-ecosystem:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-config-*"
    # Ignore specific dependencies that might cause issues
    ignore:
      # Ignore major version updates for React 19 (stable release)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Ignore major version updates for Next.js (wait for stable releases)
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "avarayr"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    # Group all GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
